remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: [Flow-IPC web site]
description: [Flow-IPC is a comprehensive C++ toolkit for latency-free interprocess communication. This site contains documentation and release links.]
