name: Flow sync-docs pipeline

on:
  # To create the button that runs a workflow manually:
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Mock Update Documentation
      run: |
        mkdir -p doc/versions/main
        echo "<h1>Hello, World!</h1>" >> doc/versions/main/index.html

    - name: Commit and push if there are changes
      run: |
        # These values informally recommended in:
        #   https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add doc
        git commit -m 'Update documentation' || exit 0   # Exit gracefully if no changes
        git push origin main
